name: yuksalish_1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  shared_preferences: ^2.0.15
  shimmer_animation: ^2.1.0+1
  carousel_slider:
  provider: ^6.0.4
  path_provider: ^2.0.11
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  sqflite: ^2.2.0+3
  anim_search_bar: ^2.0.2
  image_picker: ^0.8.6
  firebase_storage: ^11.0.10
  flutter_svg: ^1.1.6
  flutter_spinkit: ^5.1.0
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/json_ic/

  fonts:
    - family: Antique
      fonts:
        - asset: assets/fonts/Antique.ttf
